### ISSUE TITLE
Enable Duplicate Dragging of Images

### ISSUE THREAD

**Issue by AmyshaDixon** [AmyshaDixon/ProductRecomGame#11]
The drag and drop panel currently only allows one of each bird/egg to be dragged (leaving the panel empty). The user should instead be able to drag as many birds/eggs as they want (leaving the panel full) to fill their nest in order to better represent their family.

**Comment by AmyshaDixon** [comment]
Amazing job, @nelsonnyland 
![giphy](https://user-images.githubusercontent.com/38476640/63389752-9a54bf00-c361-11e9-81f3-2571361bf8b7.gif)

**Comment by nelsonnyland** [comment]
Thank you! That gif is hilarious!
